standard = "2019"
preferred_case = "lower"
[libraries]
defaultlib.files = [
    "src/*/*.vhd",
    "src/*/tb/*.vhd",
]
neorv32.files = [
    "lib/neorv32/rtl/core/*.vhd",
    "src/neorv32_extra/*.vhd",
]
